### ISSUE TITLE
Add capability to include helm repo credentials in repository.yaml

### ISSUE THREAD

**Issue by nCyberSolutions** [mesosphere/mindthegap#51]
It would be great if I could add a username and password to the repositories.yaml file to allow pulls from a private, authenticated repository:

repositories:
  jetstack:
    repoURL: https://charts.jetstack.io
    username: test-user
    password: test-password
    charts:
      cert-manager:
      - v1.7.0
      - v1.6.1

**Comment by jimmidyson** [comment]
Thanks for raising the issue! Fixed in #65 :tada:
