### ISSUE TITLE
Have your cake and eat it too?

### ISSUE THREAD

**Issue by aceeric** [mesosphere/mindthegap#755]
Folks - has there been discussion of allowing the server to serve both OCI images and helm charts in the same server instance? I have not yet dug into the code to see if thats easy/medium or hard... Thank you

**Comment by jimmidyson** [comment]
That already works! Just create a bundle with the create bundle subcommand which now creates a single bundle containing both images and helm charts (check out the flags) and serve bundle still serve everything from that single bundle. 

Alternatively create two separate bundles and specify both bundles to the the serve bundle command (which accepts multiple bundles).

Let me know if that works for you?

**Comment by aceeric** [comment]
ahhh. I had done `./mindthegap serve bundle --bundle *.tar` with:
```
ls -1 *.tar
helm.tar
images.tar
```
But: 
```
 ✓ Creating temporary directory
 ✓ Unarchiving image bundle "helm.tar"
 ✓ Parsing Helm charts bundle config
 ✓ Creating Docker registry
Listening on 127.0.0.1:46295
```
Then:
```
crane catalog localhost:46295
```
Says:
```
charts/cert-manager
```

But this works fine: 
```
./mindthegap serve bundle --bundle helm.tar,images.tar
```

Thanks!

**Comment by jimmidyson** [comment]
That's interesting that the first incantation didn't throw an error for extra args 🤷‍♂️

But happy you you it working!
